### ISSUE TITLE
1.12.13 not available on pivnet? 

### ISSUE THREAD

**Issue by aegershman** [pivotal-cf/docs-new-relic#19]
Should 1.12.13 be available? On pivnet the latest newrelic tile version available is 1.12.9, but the release notes show that 1.12.13 is the latest: https://network.pivotal.io/products/p-new-relic/

Thanks!

( duplicate of newrelic/newrelic-pcf-agent-tile#5 )

**Comment by aegershman** [comment]
@jknostman3 1.12.13 is still being referenced here: https://github.com/pivotal-cf/docs-new-relic/blob/master/index.html.md.erb#L73

[Judging on the past two commits](https://github.com/pivotal-cf/docs-new-relic/commit/499dd1993006926c38f46f83f4423ba66a4ed1f8) I'm guessing releasing 1.12.13 was accidental?

Also just so you know, newrelic 1.12.13 is still showing up in people's OpsManager UIs:

![screen shot 2018-08-09 at 3 49 20 pm](https://user-images.githubusercontent.com/5619476/43925429-d73683d8-9bec-11e8-8013-48b68c577e8e.png)
![screen shot 2018-08-09 at 3 49 26 pm](https://user-images.githubusercontent.com/5619476/43925432-d9e43594-9bec-11e8-95d8-aaa93653772e.png)

**Comment by jknostman3** [comment]
Hi @aegershman, the 1.12.13 release docs were merged too soon as 1.12.13 is not available. Thank you for catching that!
